# ==============================================================================
# variant_05.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant05_Bollinger_Bands_Filter(bt.Strategy):
    '''
    Modification: Added Bollinger Bands filter and trailing stop
    Reasoning: Enter on MA cross when price is not at extreme Bollinger levels
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('bb_period', 20),
        ('bb_dev', 2),
        ('trail_percent', 0.03),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.bb = bt.indicators.BollingerBands(
            period=self.params.bb_period,
            devfactor=self.params.bb_dev
        )
        self.order = None
        self.stop_price = None
    
    def next(self):
        if self.order:
            return
            
        if not self.position:
            if (self.crossover > 0 and 
                self.bb.lines.bot[0] < self.data.close[0] < self.bb.lines.top[0]):
                self.order = self.buy()
                
        else:
            # Trailing stop
            if self.stop_price is None:
                self.stop_price = self.data.close[0] * (1 - self.params.trail_percent)
            else:
                new_stop = self.data.close[0] * (1 - self.params.trail_percent)
                if new_stop > self.stop_price:
                    self.stop_price = new_stop
            
            if self.crossover < 0 or self.data.close[0] < self.stop_price:
                self.order = self.sell()
                self.stop_price = None
    
    def notify_order(self, order):
        if order.status in [order.Completed, order.Canceled, order.Margin]:
            self.order = None