# ==============================================================================
# variant_12.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant12_Time_Based_Exits(bt.Strategy):
    '''
    Modification: Added time-based exits and session filters
    Reasoning: Avoid holding positions too long and filter trading hours
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('max_hold_days', 10),
        ('start_hour', 9),
        ('end_hour', 15),
        ('stop_loss_pct', 0.02),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.entry_bar = None
        self.entry_price = None
    
    def next(self):
        current_time = self.data.datetime.time(0)
        current_hour = current_time.hour
        
        # Check if within trading hours
        in_session = self.params.start_hour <= current_hour <= self.params.end_hour
        
        if not self.position:
            if (self.crossover > 0 and in_session):
                self.buy()
                self.entry_bar = len(self.data)
                self.entry_price = self.data.close[0]
                
        else:
            bars_held = len(self.data) - self.entry_bar
            current_loss = (self.entry_price - self.data.close[0]) / self.entry_price
            
            if (self.crossover < 0 or 
                bars_held >= self.params.max_hold_days or
                current_loss >= self.params.stop_loss_pct or
                not in_session):
                self.sell()
                self.entry_bar = None
                self.entry_price = None