# ==============================================================================
# variant_04.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant04_ADX_Trend_Filter(bt.Strategy):
    '''
    Modification: Added ADX trend strength filter and EMA instead of SMA
    Reasoning: Only trade in trending markets, EMA responds faster than SMA
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('adx_period', 14),
        ('adx_threshold', 25),
    )
    
    def __init__(self):
        self.fast_ema = bt.indicators.ExponentialMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ema = bt.indicators.ExponentialMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ema, self.slow_ema)
        self.adx = bt.indicators.DirectionalMovementIndex(
            period=self.params.adx_period
        )
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.adx.adx[0] > self.params.adx_threshold):
                self.buy()
        else:
            if (self.crossover < 0 or 
                self.adx.adx[0] < self.params.adx_threshold):
                self.sell()