# ==============================================================================
# variant_10.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant10_Keltner_Breakout(bt.Strategy):
    '''
    Modification: Added Keltner Channels for breakout confirmation and position sizing
    Reasoning: Enter on MA cross with Keltner breakout, size based on volatility
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('keltner_period', 20),
        ('keltner_mult', 2.0),
        ('atr_period', 14),
        ('risk_per_trade', 0.02),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        
        # Keltner Channels
        self.keltner_ma = bt.indicators.ExponentialMovingAverage(
            self.data.close, 
            period=self.params.keltner_period
        )
        self.atr = bt.indicators.AverageTrueRange(period=self.params.atr_period)
        
        self.keltner_upper = self.keltner_ma + (self.atr * self.params.keltner_mult)
        self.keltner_lower = self.keltner_ma - (self.atr * self.params.keltner_mult)
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.data.close[0] > self.keltner_upper[0]):
                # Position sizing based on ATR
                account_value = self.broker.get_value()
                risk_amount = account_value * self.params.risk_per_trade
                stop_distance = self.atr[0] * 2
                position_size = risk_amount / stop_distance
                self.buy(size=position_size)
                
        else:
            if (self.crossover < 0 or 
                self.data.close[0] < self.keltner_lower[0]):
                self.sell()