# ==============================================================================
# variant_03.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant03_Volume_Confirmation(bt.Strategy):
    '''
    Modification: Added volume confirmation and MACD filter
    Reasoning: Volume confirms price moves, MACD adds momentum confirmation
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('volume_period', 20),
        ('volume_mult', 1.5),
        ('macd_fast', 12),
        ('macd_slow', 26),
        ('macd_signal', 9),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.volume_ma = bt.indicators.SimpleMovingAverage(
            self.data.volume,
            period=self.params.volume_period
        )
        self.macd = bt.indicators.MACD(
            period_me1=self.params.macd_fast,
            period_me2=self.params.macd_slow,
            period_signal=self.params.macd_signal
        )
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.data.volume[0] > self.volume_ma[0] * self.params.volume_mult and
                self.macd.macd[0] > self.macd.signal[0]):
                self.buy()
        else:
            if self.crossover < 0:
                self.sell()