# ==============================================================================
# variant_07.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant07_Partial_Exits(bt.Strategy):
    '''
    Modification: Added partial profit taking and re-entry logic
    Reasoning: Lock in some profits while letting winners run
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('profit_target1', 0.02),
        ('profit_target2', 0.04),
        ('stop_loss', 0.015),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.entry_price = None
        self.first_exit_done = False
        
    def next(self):
        if not self.position:
            if self.crossover > 0:
                self.buy(size=200)  # Buy double size for partial exits
                self.entry_price = self.data.close[0]
                self.first_exit_done = False
                
        else:
            # Calculate profit percentage
            profit_pct = (self.data.close[0] - self.entry_price) / self.entry_price
            
            # First partial exit
            if not self.first_exit_done and profit_pct >= self.params.profit_target1:
                self.sell(size=100)  # Sell half position
                self.first_exit_done = True
            
            # Full exit conditions
            if (self.crossover < 0 or 
                profit_pct <= -self.params.stop_loss or
                profit_pct >= self.params.profit_target2):
                self.sell()  # Close remaining position
                self.entry_price = None