# ==============================================================================
# variant_02.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant02_ATR_StopLoss(bt.Strategy):
    '''
    Modification: Added ATR-based stop loss and take profit
    Reasoning: Dynamic stops based on volatility provide better risk management
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('atr_period', 14),
        ('atr_stop_mult', 2.0),
        ('atr_profit_mult', 3.0),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.atr = bt.indicators.AverageTrueRange(period=self.params.atr_period)
        self.order = None
    
    def next(self):
        if self.order:
            return
            
        if not self.position:
            if self.crossover > 0:
                stop_price = self.data.close[0] - (self.atr[0] * self.params.atr_stop_mult)
                profit_price = self.data.close[0] + (self.atr[0] * self.params.atr_profit_mult)
                self.order = self.buy_bracket(
                    stopprice=stop_price,
                    limitprice=profit_price
                )
        else:
            if self.crossover < 0:
                self.order = self.sell()
    
    def notify_order(self, order):
        if order.status in [order.Completed, order.Canceled, order.Margin]:
            self.order = None