# ==============================================================================
# variant_11.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant11_OBV_Volume_Trend(bt.Strategy):
    '''
    Modification: Added OBV (On Balance Volume) and Donchian Channels
    Reasoning: Volume trend confirmation with breakout levels
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('obv_period', 14),
        ('donchian_period', 20),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        
        # On Balance Volume
        self.obv = bt.indicators.OnBalanceVolume()
        self.obv_ma = bt.indicators.SimpleMovingAverage(
            self.obv, 
            period=self.params.obv_period
        )
        
        # Donchian Channels
        self.donchian_high = bt.indicators.Highest(
            self.data.high, 
            period=self.params.donchian_period
        )
        self.donchian_low = bt.indicators.Lowest(
            self.data.low, 
            period=self.params.donchian_period
        )
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.obv[0] > self.obv_ma[0] and
                self.data.high[0] >= self.donchian_high[-1]):
                self.buy()
                
        else:
            if (self.crossover < 0 or 
                self.obv[0] < self.obv_ma[0] or
                self.data.low[0] <= self.donchian_low[-1]):
                self.sell()