# ==============================================================================
# variant_15.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant15_Multi_Indicator_Confluence(bt.Strategy):
    '''
    Modification: Combined multiple indicators for confluence-based entries
    Reasoning: Require agreement from multiple indicators before entering
    '''
    
    params = (
        ('fast_period', 12),
        ('slow_period', 26),
        ('rsi_period', 14),
        ('macd_fast', 12),
        ('macd_slow', 26),
        ('macd_signal', 9),
        ('adx_period', 14),
        ('bb_period', 20),
        ('bb_dev', 2),
        ('min_confluence', 4),  # Minimum signals needed
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.ExponentialMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.ExponentialMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.rsi = bt.indicators.RSI(period=self.params.rsi_period)
        self.macd = bt.indicators.MACD(
            period_me1=self.params.macd_fast,
            period_me2=self.params.macd_slow,
            period_signal=self.params.macd_signal
        )
        self.adx = bt.indicators.DirectionalMovementIndex(period=self.params.adx_period)
        self.bb = bt.indicators.BollingerBands(
            period=self.params.bb_period,
            devfactor=self.params.bb_dev
        )
    
    def next(self):
        if not self.position:
            # Count bullish signals
            bullish_signals = 0
            
            if self.crossover > 0:
                bullish_signals += 1
            if self.rsi[0] > 50 and self.rsi[0] < 70:
                bullish_signals += 1
            if self.macd.macd[0] > self.macd.signal[0]:
                bullish_signals += 1
            if self.adx.adx[0] > 25:
                bullish_signals += 1
            if self.data.close[0] > self.bb.lines.mid[0]:
                bullish_signals += 1
            if self.data.close[0] > self.slow_ma[0]:
                bullish_signals += 1
            
            if bullish_signals >= self.params.min_confluence:
                self.buy()
                
        else:
            # Count bearish signals for exit
            bearish_signals = 0
            
            if self.crossover < 0:
                bearish_signals += 1
            if self.rsi[0] > 70:
                bearish_signals += 1
            if self.macd.macd[0] < self.macd.signal[0]:
                bearish_signals += 1
            if self.data.close[0] < self.bb.lines.mid[0]:
                bearish_signals += 1
            if self.data.close[0] < self.slow_ma[0]:
                bearish_signals += 1
            
            if bearish_signals >= 2:
                self.sell()