# ==============================================================================
# variant_01.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant01_RSI_Filter(bt.Strategy):
    '''
    Modification: Added RSI filter to avoid entries during overbought/oversold conditions
    Reasoning: Filter out poor timing entries when momentum is exhausted
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('rsi_period', 14),
        ('rsi_overbought', 70),
        ('rsi_oversold', 30),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.rsi = bt.indicators.RSI(period=self.params.rsi_period)
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.rsi < self.params.rsi_overbought):
                self.buy()
        else:
            if (self.crossover < 0 or 
                self.rsi > self.params.rsi_overbought):
                self.sell()