# ==============================================================================
# variant_08.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant08_Williams_R_Momentum(bt.Strategy):
    '''
    Modification: Added Williams %R momentum filter and CCI confirmation
    Reasoning: Multiple momentum indicators for better entry timing
    '''
    
    params = (
        ('fast_period', 15),
        ('slow_period', 50),
        ('williams_period', 14),
        ('williams_oversold', -80),
        ('williams_overbought', -20),
        ('cci_period', 20),
        ('cci_threshold', 100),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.williams = bt.indicators.WilliamsR(period=self.params.williams_period)
        self.cci = bt.indicators.CommodityChannelIndex(period=self.params.cci_period)
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.williams[0] < self.params.williams_oversold and
                self.cci[0] > -self.params.cci_threshold):
                self.buy()
        else:
            if (self.crossover < 0 or 
                self.williams[0] > self.params.williams_overbought or
                self.cci[0] < -self.params.cci_threshold):
                self.sell()