# ==============================================================================
# variant_09.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant09_VWAP_Mean_Reversion(bt.Strategy):
    '''
    Modification: Added VWAP and modified for pullback entries
    Reasoning: Enter on pullbacks to moving averages with VWAP confirmation
    '''
    
    params = (
        ('fast_period', 20),
        ('slow_period', 50),
        ('pullback_bars', 3),
        ('max_pullback', 0.02),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        
        # VWAP calculation
        typical_price = (self.data.high + self.data.low + self.data.close) / 3
        self.vwap = bt.indicators.WeightedAverage(
            typical_price, 
            self.data.volume,
            period=20
        )
        
        self.bars_since_cross = 0
        self.cross_price = None
    
    def next(self):
        # Track bars since crossover
        if self.crossover > 0:
            self.bars_since_cross = 0
            self.cross_price = self.data.close[0]
        else:
            self.bars_since_cross += 1
            
        if not self.position:
            # Enter on pullback after bullish cross
            if (self.bars_since_cross > 0 and 
                self.bars_since_cross <= self.params.pullback_bars and
                self.cross_price is not None and
                self.data.close[0] < self.cross_price and
                (self.cross_price - self.data.close[0]) / self.cross_price <= self.params.max_pullback and
                self.data.close[0] > self.vwap[0]):
                self.buy()
                
        else:
            if (self.crossover < 0 or 
                self.data.close[0] < self.vwap[0]):
                self.sell()