# ==============================================================================
# variant_13.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant13_Ichimoku_Filter(bt.Strategy):
    '''
    Modification: Added Ichimoku Cloud components for trend and momentum
    Reasoning: Multiple Ichimoku signals for robust trend following
    '''
    
    params = (
        ('fast_period', 9),
        ('slow_period', 26),
        ('tenkan_period', 9),
        ('kijun_period', 26),
        ('senkou_period', 52),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        
        # Ichimoku components
        self.tenkan = (bt.indicators.Highest(self.data.high, period=self.params.tenkan_period) + 
                      bt.indicators.Lowest(self.data.low, period=self.params.tenkan_period)) / 2
        
        self.kijun = (bt.indicators.Highest(self.data.high, period=self.params.kijun_period) + 
                     bt.indicators.Lowest(self.data.low, period=self.params.kijun_period)) / 2
        
        self.senkou_a = (self.tenkan + self.kijun) / 2
        self.senkou_b = (bt.indicators.Highest(self.data.high, period=self.params.senkou_period) + 
                        bt.indicators.Lowest(self.data.low, period=self.params.senkou_period)) / 2
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.data.close[0] > self.senkou_a[0] and
                self.data.close[0] > self.senkou_b[0] and
                self.tenkan[0] > self.kijun[0]):
                self.buy()
                
        else:
            if (self.crossover < 0 or 
                self.data.close[0] < self.senkou_a[0] or
                self.tenkan[0] < self.kijun[0]):
                self.sell()