# ==============================================================================
# variant_14.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant14_Pyramid_Scaling(bt.Strategy):
    '''
    Modification: Added pyramiding (scaling into winners) and multiple confirmations
    Reasoning: Add to winning positions while managing risk with multiple filters
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('rsi_period', 14),
        ('volume_period', 20),
        ('max_pyramid_levels', 3),
        ('pyramid_increment', 0.01),
        ('trail_percent', 0.02),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.rsi = bt.indicators.RSI(period=self.params.rsi_period)
        self.volume_ma = bt.indicators.SimpleMovingAverage(
            self.data.volume, 
            period=self.params.volume_period
        )
        
        self.pyramid_levels = 0
        self.last_entry_price = None
        self.highest_price = None
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                30 < self.rsi[0] < 70 and
                self.data.volume[0] > self.volume_ma[0]):
                self.buy(size=100)
                self.pyramid_levels = 1
                self.last_entry_price = self.data.close[0]
                self.highest_price = self.data.close[0]
                
        else:
            # Update highest price for trailing
            if self.data.close[0] > self.highest_price:
                self.highest_price = self.data.close[0]
            
            # Pyramid logic
            if (self.pyramid_levels < self.params.max_pyramid_levels and
                self.data.close[0] > self.last_entry_price * (1 + self.params.pyramid_increment) and
                self.rsi[0] < 60):
                self.buy(size=100)
                self.pyramid_levels += 1
                self.last_entry_price = self.data.close[0]
            
            # Exit logic with trailing stop
            trail_stop = self.highest_price * (1 - self.params.trail_percent)
            if (self.crossover < 0 or 
                self.data.close[0] < trail_stop):
                self.sell()
                self.pyramid_levels = 0
                self.last_entry_price = None
                self.highest_price = None