# ==============================================================================
# variant_06.py
# ==============================================================================
# Auto-generated by Mutation Agent
# Generated: 2026-01-15 02:13:51
# ==============================================================================

import backtrader as bt

class Variant06_Multiple_Timeframes(bt.Strategy):
    '''
    Modification: Added higher timeframe trend filter (200 EMA) and Stochastic
    Reasoning: Align trades with higher timeframe trend and momentum
    '''
    
    params = (
        ('fast_period', 10),
        ('slow_period', 30),
        ('trend_period', 200),
        ('stoch_k', 14),
        ('stoch_d', 3),
        ('stoch_oversold', 20),
        ('stoch_overbought', 80),
    )
    
    def __init__(self):
        self.fast_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.fast_period
        )
        self.slow_ma = bt.indicators.SimpleMovingAverage(
            self.data.close, 
            period=self.params.slow_period
        )
        self.trend_ma = bt.indicators.ExponentialMovingAverage(
            self.data.close,
            period=self.params.trend_period
        )
        self.crossover = bt.indicators.CrossOver(self.fast_ma, self.slow_ma)
        self.stoch = bt.indicators.Stochastic(
            period=self.params.stoch_k,
            period_dfast=self.params.stoch_d
        )
    
    def next(self):
        if not self.position:
            if (self.crossover > 0 and 
                self.data.close[0] > self.trend_ma[0] and
                self.stoch.percK[0] < self.params.stoch_overbought):
                self.buy()
        else:
            if (self.crossover < 0 or 
                self.data.close[0] < self.trend_ma[0] or
                self.stoch.percK[0] > self.params.stoch_overbought):
                self.sell()